### PR TITLE
Escoria convert

### PR DESCRIPTION
**Pull request by matiasbian**
Hello. I converted the game to use Escoria.

The dialog tree is 60% completed, so you can try how the game works with Escoria.
Hope you like it. If you need some fixes, documentation or whatever you want just tell me.
-all the escoria's game resources are in res://scenes/Escoria

### CODE REVIEW

**Comment by JenniBee** [comment]
Wow. Awesome. I didn't expect you to get this far that fast. :)

I'll check this out this afternoon.

**Comment by matiasbian** [comment]
Great. If you need me to add or change something, just tell me

**Comment by JenniBee** [comment]
Nice job in getting the dialog trees in there. 👍 

The text, images, music, etc. still needs to be adjusted, but since you can get through the dialog in this, I'll merge it, and then we can work on updating it in-tree.

**Comment by matiasbian** [comment]
Great !  Anything you need just let me know

**Pull request merged**
